sudo: false

language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - nightly

services:
  - mysql

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - mysql -V

script:
  - php src/Ifsnop/Mysqldump/Mysqldump.php
  - cd tests && ./test.sh
